apiVersion: v2
name: north
description: GTD-inspired task management system built with Rust/Leptos
type: application
version: 0.1.6
appVersion: "0.2.1"
home: https://github.com/zorya-development/north
sources:
  - https://github.com/zorya-development/north
maintainers:
  - name: Anton Shuvalov

dependencies:
  - name: postgresql
    version: "~16.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
