[package]
name = "north-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = "0.7"
pulldown-cmark = "0.12"
ammonia = "4"
web-sys = { version = "0.3", features = [
    "DomRect",
    "Element",
    "HtmlElement",
    "CssStyleDeclaration",
    "Window",
] }
