[package]
name = "north-dto"
version = "0.1.0"
edition = "2021"

[dependencies]
north-recurrence = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
fractional_index = "2.0"
