[package]
name = "north-repositories"
version = "0.1.0"
edition = "2021"

[features]
ssr = ["north-server-fns/ssr"]
hydrate = ["north-server-fns/hydrate"]

[dependencies]
north-dto = { workspace = true }
north-server-fns = { workspace = true }
leptos = "0.7"
